# ===============================================================
# TELECARE BACKEND - DEVELOPMENT PROFILE
# ===============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Development OpenApi
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Bootstrap Admin enabled for local convenience
homespace.bootstrap.admin.enabled=${BOOTSTRAP_ADMIN_ENABLED:true}

# Logging
logging.level.com.hs.user=DEBUG
logging.level.org.springframework.security=DEBUG
